steps:
# build step for compiling java file.
- name: 'gcr.io/cloud-builders/javac'
  args: ['@javaClasses']
artifacts:
   objects:
      location: 'gs://cloud_build_bucket/files'
      paths: ['*java','cloudbuild.yml','Simple.class','Demo.class'] 


