steps:
# build step for building image demo-image:latest
- name: 'gcr.io/cloud-builders/docker'
  args: ['build','-t','demo-image:v3.0','.']
# build step for tagging the image tag=gcr.io/${PROJECT_ID}
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag','demo-image:v3.0','gcr.io/${PROJECT_ID}/demo-image:v3.0']
# build step for pushing an image to gcr as part of build step.
- name: 'gcr.io/cloud-builders/docker'
  args: ['push','gcr.io/${PROJECT_ID}/demo-image:v3.0']
# pushing image demo-image to gcr as part of images array.
images: ['gcr.io/${PROJECT_ID}/demo-image:v3.0']


