steps:
# build step for fetching the source code.
- name: 'gcr.io/cloud-builders/git'
  args: ['clone','https://github.com/akshay-jedhe/SpringBootProjects.git']
# build step for building the docker image of spring-boot project
- name: 'gcr.io/cloud-builders/docker'
  dir: './SpringBootProjects/'
  args: ['build','-t','gcr.io/${PROJECT_ID}/myproject-image:v2.0','.']
# build step for pushing image to gcr
- name: 'gcr.io/cloud-builders/docker'
  args: ['push','gcr.io/${PROJECT_ID}/myproject-image:v2.0']
# build step for deploying application on kubernetes (gke) cluster
- name: 'gcr.io/cloud-builders/gke-deploy:stable'
  dir:  './SpringBootProjects/'
  args: ['apply','--filename=./k8s-config/','--location=us-central1-a','--cluster=standard-cluster-1']

  
