steps:
# build step for fetching the source code.
- name: 'gcr.io/cloud-builders/git'
  args: ['clone','https://github.com/akshay-jedhe/SpringBootProjects.git']
# build step for building the docker image of spring-boot project
- name: 'gcr.io/cloud-builders/docker'
  dir: './SpringBootProjects/'
  args: ['build','-t','gcr.io/${PROJECT_ID}/myproject-image:latest','.']
# build step for pushing image to gcr
- name: 'gcr.io/cloud-builders/docker'
  args: ['push','gcr.io/${PROJECT_ID}/myproject-image']
# build step for runing the image
- name: 'gcr.io/cloud-builders/docker'
  args: ['run','-d','--name=myapp','-p=30001:30001','gcr.io/${PROJECT_ID}/myproject-image']
  
