steps:
# immediately running step.
- name: 'centos'
  args: ['echo','BUILD-ID : ${BUILD_ID}']
  waitFor:
  - '-'
# first step going to run
- name: 'gcr.io/cloud-builders/docker'
  args: ['build','-t','custom-nginx','.']
  id: 'build-phase'
# step wait until the build phase complete its execution successfully.
- name: 'gcr.io/cloud-builders/docker'
  args: ['run','-d','--name=my-nginx-ctn','custom-nginx']
  id: 'run-phase'
  waitFor:
  - 'build-phase'


